# Generated by Django 4.1 on 2022-09-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdrugrel",
            name="drug_name",
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
