# Generated by Django 4.1 on 2022-09-18 10:39

from django.db import migrations, models
import django_extensions.db.fields
import drug_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        validators=[drug_app.validators.NameValidator()],
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[drug_app.validators.integer_length]
                    ),
                ),
                ("exp_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True
                    ),
                ),
                (
                    "updated_at",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DrugLike",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        validators=[drug_app.validators.NameValidator()],
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[drug_app.validators.integer_length]
                    ),
                ),
                ("exp_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True
                    ),
                ),
                (
                    "updated_at",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
