# Generated by Django 4.1 on 2022-09-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drug_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
